name: Ci, Lint, Build
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Ci, Lint, Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: CI
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Test Build
        run: npm run build